CREATE TABLE nodes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type          VARCHAR(30) NOT NULL,
    inserted_ts   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE edges (
    source_id         BIGINT NOT NULL,
    target_id         BIGINT NOT NULL,
    type              VARCHAR(50) NOT NULL,
    specific_metadata JSONB,
    inserted_ts       TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (source_id, target_id, type),
    FOREIGN KEY (source_id) REFERENCES nodes(id),
    FOREIGN KEY (target_id) REFERENCES nodes(id)
);

CREATE TABLE files (
    id               BIGINT PRIMARY KEY,
    root_name        VARCHAR(160) NOT NULL,
    version_number   INTEGER NOT NULL,
    sha256_hash      CHAR(64) NOT NULL,
    extension        VARCHAR(16) NOT NULL,
    size             BIGINT NOT NULL,
    specific_metadata JSONB,
    description      TEXT,
    FOREIGN KEY (id) REFERENCES nodes(id)
);

CREATE TABLE storage_devices (
    id     BIGINT PRIMARY KEY,
    name   VARCHAR(160) NOT NULL,
    size   BIGINT NOT NULL,
    path   VARCHAR(160),
    FOREIGN KEY (id) REFERENCES nodes(id)
);

CREATE TABLE collections (
    id          BIGINT PRIMARY KEY,
    name        VARCHAR(160) NOT NULL,
    description TEXT,
    FOREIGN KEY (id) REFERENCES nodes(id)
);


